### ISSUE TITLE
Proposal document URL returns 404

### ISSUE THREAD

**Issue by MariaCheca** [AyuntamientoMadrid/consul#1280] opened 2018-02-19 19:36 UTC
[This proposal's documents](https://decide.madrid.es/proposals/19914-incineradora-de-valdemingomez-no) URLs returns a 404 code. Looks like somehow the internal link is broken or missing, but the `Document` object is correctly stored in ddbb with the right ids and references.

```
ActionController::RoutingError: No route matches [GET] "/system/documents/attachments/000/000/060/original/4a814ef7aecebe8b5b09e4cc0074b6a14b57a442.pdf"
```

More information about this occurrence in Rollbar: https://rollbar.com/consul/Participacion/items/974/?item_page=18&#traceback

**Comment by aitbw** [comment] 2018-02-21 13:49
I'm on it

**Comment by aitbw** [comment] 2018-02-21 15:15
To keep track of this bug: [This proposal](https://decide.madrid.es/proposals/19467-propuesta-de-la-nueva-linea-13-de-metro-mirasierra-sanchinarro-valdebebas-t4)'s document also returns a 404 code

**Comment by aitbw** [comment] 2018-02-23 17:18
[This one](https://decide.madrid.es/proposals/19520-parar-la-construccion-de-microbarrio-en-distrito-san-blas-canillejas) also returns a 404 code

We have 2 patterns by now: All the issues were created in October 2017 and Proposals seems the only model affected as [this one](https://decide.madrid.es/presupuestos/presupuestos-participativos-2018/proyecto/10262) works without problems.

**Comment by aitbw** [comment] 2018-02-23 17:21
[Another one](https://decide.madrid.es/proposals/19489-rotonda-canillejas-a2-av-logrono-cl-alcala)

**Comment by aitbw** [comment] 2018-02-27 15:01
# UPDATE (27/02/2018)

This error has been reproduced locally. Steps to follow:

1. Log in as an user (any user capable to create a Proposal will do)
2. Create a Proposal with a document attached to it
3. Kill your Rails server
4. Generate a new secret with `bundle exec rake secret` and replace it accordingly under `config/secrets.yml#secret_key_base`
5. Start the Rails server again
6. Go to the Proposal you created a few minutes ago and try to download the attached document

Since this has to do with the app's `secret_key_base`, it's possible the URLs to download attachments created **previous** to [October 2017](https://github.com/AyuntamientoMadrid/consul/issues/1280#issuecomment-368076178) are also broken

**Comment by bertocq** [comment] 2018-02-27 15:07
@aitbw So you mean that we might have changed `config/secrets.yml` value for 
```yaml
production:
  secret_key_base:
```
around that time and it broke all previously created attachment urls, right?

Is there a way to re-create & fix all those urls with a rake task?

**Comment by aitbw** [comment] 2018-02-27 15:29
Yes, that's correct @bertocq

Paperclip has several built-in Rake tasks to fix this **but** they only seem to work with `document.attachment.url` which is what's generating the incorrect routes so we need to find a way to update this

**Comment by bertocq** [comment] 2018-03-02 10:24
https://decide.madrid.es/proposals/19914-incineradora-de-valdemingomez-no still has broken document links, reverting PR merge

**Comment by aitbw** [comment] 2018-03-02 16:00
To get some insight on this one: Did you check, by any chance, if the other reported proposals worked with the fix introduced on #1307, @bertocq?

**Comment by bertocq** [comment] 2018-03-02 19:04
I checked other proposals & investments older  than October, as well as newer (to see if newer worked correctly at least)

The problem with this is that it can't be tested at Preproduction environment, as the Preproduction environment gets a dump of the Production database every monday... but it doesn't get the files :( so all the links are broken (we've an issue to fix it https://github.com/AyuntamientoMadrid/consul/issues/1308) And testing this at PRO is not a good idea like any other kind of testing.

**Comment by aitbw** [comment] 2018-03-02 19:15
:sweat_smile: then how do we know for sure #1307 is not the solution?

**Comment by bertocq** [comment] 2018-03-02 19:17
Because neither the mentioned proposals or other older ones got their document links fixed. 

Or do you mean how are we going to figureout what's the problem and the fix for it?

**Comment by aitbw** [comment] 2018-03-02 19:20
But if you tested this only in Pre and the files are not there, they will stay broken

Try this: [This issue](https://decide.madrid.es/proposals/19467-propuesta-de-la-nueva-linea-13-de-metro-mirasierra-sanchinarro-valdebebas-t4) also has a broken document link for the file for it is [here](https://decide.madrid.es/system/documents/attachments/000/000/006/original/3779c5bafc46109e4b9f57fbeecf680b5224c302.pdf) (Shoutout to @MariaCheca for her help here :heart:)

If the URL generated with my patch is the same as the second link above, then it's fixed :smile:

**Comment by bertocq** [comment] 2018-03-02 19:23
Sorry I didn't express myself well. I checked this in PRE, and found it PRE is not the right environment. Then I checked in PRO (as stated at https://github.com/AyuntamientoMadrid/consul/issues/1280#issuecomment-369883434) and found out it wasn't working.

So to be clear: I tested in PRE and in PRO and in neither worked (at PRE it's just impossible)

**Comment by aitbw** [comment] 2018-03-02 19:29
Well, technically it's not impossible since Pre works with a Pro DB dump so all data should stay the same so you can tell if the URL generated is correct or not —obviously, it won't work as expected since the actual files are not on the Pre server but you get the idea

Anyway, thanks for the clarification @bertocq, I'll keep on researching :ok_hand:

**Comment by bertocq** [comment] 2018-03-02 19:32
🤔  you're right! Just changing the pre url for pro would allow to check it solution is right at PRE servers without deploying to pro :)

Can you gather some of those url's that we should check at PRE next time we try a solution? Or at least share those that you've used for the research

**Comment by aitbw** [comment] 2018-03-02 19:41
See my comments above soon as I picked this issue; I found 4 proposals with broken documents links and a budget investment project that works without problems

**Comment by bertocq** [comment] 2018-03-07 14:56
Production url's are broken for documents created after the problem origin (suppossed to be october)

Budget::Investment: https://decide.madrid.es/presupuestos/presupuestos-participativos-2018/proyecto/8535
Proposal: https://decide.madrid.es/proposals/20602-ampliacion-de-la-acera
Poll: https://decide.madrid.es/vota/rehabilitacion-plaza-duquesa-osuna

I'm taking over this issue

**Comment by bertocq** [comment] 2018-03-07 19:22
There was multiple issues:
- Files that still got attachment title as the file_name (only 4 from before the file name was ofuscated) Those 4 documentables have gotten broken links since then
- Files that neither the `attachment_file_name` nor the filename in the right folder had anything in common with the `attachment.url` string generated
- Files that had either the `attachment_file_name` or the filename at its folder right....

Was able to confirm that most noticed problem was originated by a change in the production.secret_key_base key. Issue fixed at Production shared folder by fixing all document filenames to match the attachment.url value.

Nothing to backport. Although some forks might have similar problems that will only be possible to fix manually as we did, no silver bullets here.

**Closed by bertocq** 2018-03-07 19:22 UTC
Labels: Bug, High priority
